### PR TITLE
Update outdated dependencies and bump python version to 3.8

### PR DESCRIPTION
**Pull request by povilasAntanavicius**
# Pull Request Template

## Description
Update insecure dependencies and boosted python version for debian10 from 3.7 to 3.8  

## Code changes
Update docker images and setup scripts, updated pillow dependency to use version `10.2.0`. Additional changes were done for panda 2.0 removing append feature.

- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [x] Vulnerability mitigation update (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new Warnings, errors, bugs
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by ernestask — APPROVED** [review]
+6.9

**Comment by Jauler** [comment]
> +6.9

OOoh, long time no see :wave:

**Comment by povilasAntanavicius** [comment]
@packgron please review

**Review by packgron — APPROVED** [review]
+2.0

**Pull request merged**
